name: release
on:
  push:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image BACKEND and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/backend.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Build image FRONTEND and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/frontend.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}